mysociety/theyworkforyou

www/docs/admin/websites.php
End bracket from INSERT statement was missing causing it to fail.
Fixes #739
=> Fix missing bracket in MP URL SQL

www/docs/style/sass/pages/_section.scss
=> Styled qna attachments and statements

www/docs/admin/reporting_stats.php, www/includes/easyparliament/metadata.php, www/includes/easyparliament/page.php
tracks monthly signups so devs don't have to rootle this out the DB.
Start of #105
=> add a reporting stats page to admin pages

www/docs/style/sass/pages/_section.scss
Small display-related bugfixes. Closes #765, #768
=> Debate pages design bugfixes

.gitignore, Gemfile, Gemfile.lock, bin/deploy.bash, conf/packages, www/includes/easyparliament/page.php, www/includes/easyparliament/templates/html/header.php, www/includes/utility.php
=> Add cache busting function for CSS and JavaScript, and use bundler

.scrutinizer.yml, classes/Renderer.php, www/docs/admin/glossary_pending.php, www/docs/api/index.php, www/docs/departments/index.php, www/docs/departments/questions.php, www/docs/departments/statements.php, www/docs/email/index.php, www/docs/freeourbills/share.php, www/docs/gadget/bbc.php, www/docs/gadget/pc.php, www/docs/regmem/index.php, www/docs/video/index.php, www/docs/vote/index.php, www/includes/easyparliament/comment.php, www/includes/easyparliament/commentlist.php, www/includes/utility.php
=> Parameterize a few missing db queries.

db/0002-add-estimated_usage-to-api_key.sql, db/schema.sql, www/docs/api/index.php, www/docs/api/key.php
Adds a basic API pricing page with a table of prices and links to it from the
API homepage.
@struan, @jacksonj04, @dracos - When you have a mo, would you mind sanity
checking the way I've added this page to make sure it fits in with the way
TWFY does things?
@BenJam, @MyfanwyNixon, @steiny, @abimysoc - I'm guessing the copy and pricing
details here are going to need some finesse - consider this a starter for ten!
I'll add a screenshot in a mo..
Closes #152
=> Add an API pricing page

www/docs/style/sass/app.scss, www/docs/style/sass/pages/_action.scss, www/includes/easyparliament/templates/html/action/where-next.php
Spent basically no time on this at all, but main differences are:
* Clearer distinction between the introduction and the options in the main body
* More legible line lengths
* White background for most of the text
Folds up nicely on narrow screens, as you'd expect.
=> Basic styling for actions page elements

db/0004-add-research-qual2-log.sql, db/schema.sql, www/docs/js/qual2.js, www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/section/section.php, www/includes/easyparliament/templates/research/qual2.php
1. Randomly assigns a user visiting either a person or speech page to either a treatment or control group.
2. Records a page view.
3. Shows any necessary treatment.
4. Records any interactions with the treatment.
=> Implement "Where Next?" research tracking

www/docs/privacy/index.php, www/includes/easyparliament/page.php, www/includes/easyparliament/staticpages/help.php, www/includes/easyparliament/templates/html/footer.php
=> Remove Extreme DB tracking code and update policy pages accordingly.

www/includes/easyparliament/templates/html/index.php, www/includes/easyparliament/templates/html/ni/index.php, www/includes/easyparliament/templates/html/scotland/index.php
Adds tracking of submit events to the postcode form on the home page (similar to the search form).
=> Add submission tracking to homepage postcode form

classes/Gid.php, classes/Homepage.php
Make sure that if the gid for the featured debate has been redirected we
follow it rather than displaying nothing.
Fixes #873
=> Redirect gid for featured debate if required

www/docs/regmem/index.php
This only affected the "diff" pages, not the list on the MP page itself.
The XML no longer contains 'memberid', so make looking for that
optional. The categories changed at the election, so add capability for
spotting them being different in a comparison/history.
=> Fix Register post election.

classes/Renderer.php, classes/Renderer/User.php, classes/SectionView/SectionView.php, www/docs/glossary/index.php, www/docs/style/sass/app.scss, www/docs/style/sass/pages/_legacy.scss, www/docs/user/index.php, www/includes/easyparliament/page.php, www/includes/easyparliament/templates/html/header.php
This is to move all the remaining pages over to the new design by at least wrapping them in the new header and footer, plus a bit of fixup CSS and HTML to correct the worst issues.
Fixes #938
=> Output new header/footer from old page class

www/includes/easyparliament/templates/html/static/help.php
Updated vote text plus some coverage of common user support queries.
Fixes #902
=> Rewritten help/FAQ page

classes/AlertView/Standard.php, classes/Search.php, classes/Utility/Search.php, www/includes/easyparliament/alert.php, www/includes/easyparliament/templates/html/search/results.php
also do the same in the spelling correction so it's a bit easier for
people to read.
Fixes #944
=> swap speaker:$id in search results for name

scripts/json2db.pl
If we skip the whole of the vote processing of a motion then it's
possible that a policy that only contains motions that are in other
policies never has the has_strong_vote mp info set and so always
displays as not having enough information to decide a position.
This moves the check into the motions loop and only skips the setting of
the vote information in the persondivisionvotes table. We also move
setting the motion_seen code to after the vote processing to avoid
always skipping updates.
Fixes #961
=> Always process checks for strong votes in motions

www/docs/style/sass/layout/_footer.scss, www/includes/easyparliament/templates/html/footer.php
Fixes #874. Wording from @MyfanwyNixon.
=> Higher contrast and better layout for footer newsletter signup box

www/docs/mp/index.php, www/includes/easyparliament/templates/html/index.php, www/includes/easyparliament/templates/html/mp/divisions.php, www/includes/easyparliament/templates/html/mp/error.php, www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/mp/votes.php, www/includes/easyparliament/templates/html/search/sidebar.php, www/includes/easyparliament/templates/html/static/contact.php, www/includes/easyparliament/templates/html/static/help.php
Fixes a number of small issues with the text.
=> Various small text tweaks

scripts/mpinfoin.pl, www/docs/mp/index.php
Also improve the code to work out the latest stats available for the MP
Fixes #580
=> update to use latest WTT responsiveness stats

www/includes/easyparliament/templates/html/alert/index.php
=> Add AdWords conversion tracking to alert signup confirmation

www/includes/easyparliament/templates/html/footer.php
Data on how many people use the footer signup form would help us work out whether the signup form should be included in the new standard footer (https://github.com/mysociety/theyworkforyou/issues/1095).
=> Google Analytics event tracking for footer mailing list signup form

scripts/mpinfoin.pl, www/docs/mp/index.php, www/docs/style/sass/_twfy-mixins.scss, www/docs/style/sass/app.scss, www/docs/style/sass/pages/_home.scss, www/docs/style/sass/pages/_mp.scss, www/docs/style/sass/parts/_panels.scss, www/includes/easyparliament/templates/html/index.php, www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/mp/votes.php
**Ready for review?**
Big eye-catching banner on the MP page, which will need wiring up with real data by @struan. (Fixes #1098.)
And also big banner on homepage, which needs some more enticing copy from @MyfanwyNixon once we have some juicy statistics to pick out. (Fixes #1096.)
=> WIP: Promote MP responsiveness on TWFY homepage and MP profile page

classes/Renderer.php, www/docs/style/sass/parts/_panels.scss, www/includes/easyparliament/templates/html/header.php, www/includes/easyparliament/templates/html/mp/profile.php
This adds in Facebook and twitter buttons to the referendum stance panel.
It also makes some small visual improvements and adds a source.
=> Add sharing to EU ref stance

classes/Search.php, classes/Search/ParseArgs.php, www/docs/style/sass/pages/_search.scss, www/includes/easyparliament/templates/html/search/form_main.php
=> add back in search all speeches/$person's speeches radio buttons

www/includes/easyparliament/templates/html/footer.php
Tweak the recently added UTM tag in the footer, to match our new standard: https://wiki.mysociety.org/wiki/Google_Analytics#Custom_Campaigns
=> Standardise footer UTM tracking with other sites

www/includes/easyparliament/templates/html/header.php
=> Use HTTPS links for TWFY sites that support it

www/includes/easyparliament/templates/html/static/houserules.php
Attempting to make them clearer and more modern as per #1182
Closes #1182
=> Updated house rules

www/includes/easyparliament/templates/html/section/_calendar.php
=> Link to Lords debates from per day lords calendar

classes/Divisions.php, classes/PolicyPositions.php, tests/VotesTest.php, www/docs/mp/index.php, www/docs/style/sass/pages/_mp.scss, www/includes/easyparliament/templates/html/mp/_vote_description.php, www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/mp/votes.php
**Work in progress**
Fixes #1125.
=> Show vote data under human-readable voting summaries

classes/Divisions.php, tests/VotesTest.php, www/docs/mp/index.php, www/includes/easyparliament/templates/html/mp/divisions.php, www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/mp/votes.php
Should hopefully alleviate issues where we've not updated the
information since an important vote and hence the voting record
doesn't take it into account
=> WIP display last updated dates for policy sets

www/includes/easyparliament/templates/html/mp/profile.php
remove the banner and move the statement down into the profile section
of the page.
Now looks like: 
Fixes #1122
=> move MP EU referendum campaigning statement to profile

www/includes/easyparliament/templates/html/header.php, www/includes/easyparliament/templates/html/mp/profile.php
Track clicks on Facebook like buttons and on links to MP's social media accounts.
=> Analytics social media improvements

www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/people/index.php, www/includes/easyparliament/templates/html/section/_section_content.php
Make sure that interesting links on the profile page contain http
at the start before displaying them.
Fixes #1236
=> minimal sanity checking on interesting links before display

classes/Divisions.php, conf/httpd.conf, tests/DivisionsTest.php, tests/_fixtures/divisions.xml, www/docs/mp/index.php, www/docs/style/sass/pages/_mp.scss, www/includes/easyparliament/templates/html/mp/_division_description.php, www/includes/easyparliament/templates/html/mp/_vote_footer.php, www/includes/easyparliament/templates/html/mp/divisions.php, www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/mp/recent.php, www/includes/easyparliament/templates/html/mp/votes.php
As part of making it a bit easier to see recent things that have happened this adds a page to MP's profiles which show the most recent votes they have, or have not, participated in.
As ever it's only the ones that are associated with a policy we are interested in from PW so there will need to be some words about that, or another solution.
=> Show recent votes by an MP

classes/Divisions.php, classes/Renderer/Header.php, db/0012-add-totals-to-policy-divisions.sql, db/schema.sql, scripts/json2db.pl, tests/DivisionsTest.php, tests/_fixtures/divisions.xml, www/docs/divisions/division.php, www/docs/divisions/index.php, www/includes/easyparliament/metadata.php, www/includes/easyparliament/templates/html/divisions/_vote_description.php, www/includes/easyparliament/templates/html/divisions/_vote_list.php, www/includes/easyparliament/templates/html/divisions/index.php, www/includes/easyparliament/templates/html/divisions/vote.php, www/includes/utility.php
This adds a recent votes section which lists the 30 most recent votes in the commons, as well as providing per vote pages with a list of those voting and some summary information.
Fixes #37
=> Recent Votes section

classes/Divisions.php, conf/httpd.conf, www/docs/divisions/division.php, www/docs/style/sass/pages/_section.scss, www/includes/easyparliament/templates/html/divisions/_vote_description.php, www/includes/easyparliament/templates/html/divisions/_vote_summary.php, www/includes/easyparliament/templates/html/divisions/index.php, www/includes/easyparliament/templates/html/divisions/vote.php, www/includes/easyparliament/templates/html/mp/_division_description.php
Builds on the work in #1242 to show how a specific MP voted in a vote. Also links that to the MP voting pages. It also highlights if their vote was in agreement or disagreement with the majority of MPs.
Fixes #603
=> Display individual votes for a specific MP

www/includes/easyparliament/sidebars/userlogin.php
A teeny tiny change. Fixes #1261.
=> Update message shown on login page sidebar

tests/HousesTest.php, www/includes/easyparliament/commentlist.php, www/includes/easyparliament/init.php, www/includes/easyparliament/searchengine.php
Part of [Refactoring Part 2](https://github.com/mysociety/theyworkforyou/projects/1)
=> Autoload Refactoring 2: dbtypes.php

classes/User.php, tests/FetchPageTestCase.php, tests/UserPageTest.php, tests/_fixtures/user.xml, www/docs/user/index.php, www/includes/easyparliament/user.php
Also add some basic tests for the /user pages
=> add missing pg value to user edit page

classes/EditQueue.php, classes/GlossaryEditQueue.php, www/docs/admin/glossary.php, www/docs/admin/glossary_pending.php, www/includes/easyparliament/glossary.php
Part of [Refactoring Part 2](https://github.com/mysociety/theyworkforyou/projects/1)
Prerequisite: #1327
=> Autoload Refactoring 7: editqueue.php

www/docs/api/index.php
Part of https://github.com/mysociety/jkan/issues/6.
=> Link to data.mysociety.org on API homepage intro

www/docs/style/sass/layout/_footer.scss, www/includes/easyparliament/templates/html/footer.php, www/includes/easyparliament/templates/html/header.php, www/includes/easyparliament/templates/html/static/privacy.php
Fixes #1329 by updating the privacy polict.
Fixes #1358 by adding a link to the _mySociety_ privacy policy near the newsletter signup form in the footer.
=> Update privacy policy

classes/EditQueue.php, classes/Member.php, www/docs/api/api_getLord.php, www/docs/api/api_getMembers.php, www/docs/api/api_getPerson.php, www/docs/mps/speaker09.php, www/includes/dbtypes.php, www/includes/easyparliament/hansardlist.php, www/includes/easyparliament/people.php, www/includes/easyparliament/templates/api/hansard_gid.php, www/includes/easyparliament/templates/html/search/by-person.php, www/includes/easyparliament/user.php
Replaced magic numbers with constants.
Updated SQL queries.
Verified that tests are passing.
=> Fixes #665 Convert remainder of house-based queries to use house constants

www/docs/style/sass/layout/_header.scss, www/includes/easyparliament/templates/html/header.php
**Awaiting blog post URL, then this can be merged and deployed.**
Fixes #1352.
Wording needs approval from @MyfanwyNixon.
I tried a Suffragette flag (purple, white, green) but it looked super messy.
=> Banner for National Democracy Week

www/docs/style/sass/layout/_header.scss, www/includes/easyparliament/templates/html/header.php
This reverts commit 9b43354870bc56334678e5970bde93f4df9348c4.
Closes #1375
=> Revert "Banner for National Democracy Week"

www/includes/easyparliament/hansardlist.php, www/includes/easyparliament/searchengine.php
Fixes https://github.com/mysociety/theyworkforyou/issues/664
Fixes #1386
=> Placement bug, /e removal

classes/Divisions.php, classes/Party.php, db/0017-split-up-policies-divisions.sql, db/schema.sql, scripts/json2db.pl, tests/_fixtures/divisions.xml, tests/_fixtures/party.xml, tests/_fixtures/topics.xml, www/includes/easyparliament/templates/html/mp/_division_description.php, www/includes/easyparliament/templates/html/topic/topic.php
=> Factor out policydivisions table into two tables

scripts/alertmailer.php, tests/DivisionsTest.php
(Will want to view with whitespace ignored)
=> Alert on votes

classes/AlertView.php, classes/AlertView/Standard.php, classes/Utility/Alert.php, www/docs/style/sass/_twfy-mixins.scss, www/docs/user/index.php, www/includes/easyparliament/alert.php, www/includes/easyparliament/templates/html/alert/_list.php, www/includes/easyparliament/templates/html/alert/index.php, www/includes/easyparliament/templates/html/user/form.php, www/includes/easyparliament/templates/html/user/index.php, www/includes/easyparliament/templates/html/user/join.php, www/includes/easyparliament/templates/html/user/view_user.php
This reimplements the old branch and fixes #737.
=> Add Delete All, and swap columns

classes/Divisions.php, classes/Homepage.php, classes/SPHomepage.php, www/docs/style/sass/pages/_home.scss, www/includes/easyparliament/templates/html/index.php
Fixes #1101.
Used to look like:
=> [WIP] Display recent votes on homepage

www/docs/topic/topic.php
=> Refer to classes using stricter namespacing rules

classes/Db/Connection.php, classes/FacebookLogin.php, classes/PolicyPositions.php, classes/Subscription.php, classes/TestStripe.php, tests/AcceptApiTest.php, tests/FetchPageTestCase.php, tests/TWFY_Database_TestCase.php, www/docs/api/hook.php, www/docs/api/key.php, www/docs/api/update-card.php, www/docs/js/payment.js, www/docs/style/sass/pages/_api.scss, www/docs/style/sass/spinner.scss, www/includes/easyparliament/hansardlist.php, www/includes/easyparliament/member.php, www/includes/easyparliament/searchlog.php, www/includes/easyparliament/templates/emails/api_cancelled.txt, www/includes/easyparliament/templates/emails/api_payment_failed.txt, www/includes/easyparliament/templates/html/api/check.php, www/includes/easyparliament/templates/html/api/key-form.php, www/includes/easyparliament/templates/html/api/subscription_detail.php, www/includes/easyparliament/templates/html/api/update.php
This should be for all intents and purposes identical to https://github.com/mysociety/mapit.mysociety.org/pull/103 with minor changes for the flow differences (grr). Everything in @davea original review there should already be applied here.
=> Changes to Stripe signup for SCA

www/includes/easyparliament/templates/html/header.php, www/includes/easyparliament/templates/html/mp/profile.php
As requested by @ashapond.
* Crowdfunder banner on main MP profile page (in addition to the `/votes` page).
* Button in the page topper is now red, rather than green.
=> Crowdfunder tweaks

scripts/alertgonemps.php, www/includes/easyparliament/templates/emails/alert_gone.txt
Should be replaced by the generic donation link after crowdfunder is finished.
=> Amended link to sign-up for alerts from new MP

www/includes/easyparliament/templates/html/user/form.php, www/includes/easyparliament/templates/html/user/join.php
Addresses #1500.
Changed opt-in email language to reflect general newsletter
=> Updated opt-in language

classes/Stripe.php, classes/Subscription.php, classes/TestStripe.php, www/docs/api/key.php, www/docs/api/update-card.php, www/includes/easyparliament/user.php
If someone updates their email address and has a Stripe subscription, also update the email we hold for them there.
Fixes https://github.com/mysociety/theyworkforyou/issues/1506
=> Update email in Stripe if changed on TWFY

www/includes/easyparliament/templates/emails/alert_mailout.txt
Adds survey link to email template to start survey described in #1537.
=> Added alert survey link to email template

search/index.pl, search/indexall.sh
This includes commits to fix the following issues with the Xapian indexer:
* Ensure person redirects are honoured (fixes #1530)
* Update the script to index everything to include all dates from 1919 to present
* Ensure the date format for the NI Speaker exceptions matches
=> Various Xapian indexer fixes

www/includes/easyparliament/templates/emails/alert_mailout.txt
Removing survey link ahead of analysis next week.
=> Remove email alerts survey link

classes/Subscription.php, www/docs/api/update-plan.php, www/docs/style/sass/pages/_api.scss, www/includes/easyparliament/templates/html/api/update.php
Same change as for https://github.com/mysociety/mapit.mysociety.org/pull/120
=> Catch errors at Stripe customer creation.

.github/workflows/default.yml, .gitignore, Dockerfile, bin/docker-entrypoint.sh, classes/Redis.php, composer.lock, conf/general-example, conf/packages, docker-compose.yml, scripts/future-fetch.py, scripts/morningupdate, scripts/photo-attribution-import.py, www/docs/fcgi/php-basic
This is all needed for the migration project. I've slightly refactored the compose environment to make it easier to run the unit tests locally, but I think perhaps we can revisit #1590 and merge this all together (I'd forgotton about that PR when I started, but I need to get the rest of the changes tested and approved so we're ready to go with the migration and upgrade before rviewing that).
=> Debian Bullseye, Sentinel support and various small fixes

www/includes/easyparliament/templates/html/mp/_covid19_panel.php
Add an extra bit of info at the top, saying we are bringing the records up to date. 
"There are currently votes on relevant topics that are not included in the summaries below. We are working on bringing these records up to date over the next few months. "
=> Update voting disclaimer in advance of update

www/docs/postcode/index.php, www/docs/postcode/repexplain.php, www/includes/easyparliament/page.php
In anticipation of the Welsh Parliament, and improving information on Scotland and Northern Ireland, this pulls in the text from WriteToThem to improve the postcode page.
=> More info on multi rep page

locale/TheyWorkForYou.pot, locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po, www/docs/postcode/index.php
Two small translation tweaks on first day feedback.
=> Wales translation updates

locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po, www/includes/easyparliament/templates/html/mp/_stale_data_panel.php, www/includes/easyparliament/templates/html/mp/votes.php, www/includes/easyparliament/templates/html/static/about.php
- Minor amend to about page. 
- Re-add stale data warning while we get that updated.
=> Misc text updates

.devcontainer/auto-quick-setup/devcontainer.json, .devcontainer/devcontainer.json, scripts/quick-populate
There were some issues using the auto-population devcontainer to create a prebuild.
Have now tested this in a branch, and works well.
Will merge this myself in a few days as it doesn't touch anything apart from the flow I use.
=> Amend auto-population devcontainer

www/includes/easyparliament/templates/html/mp/_stale_data_panel.php
(Going to self approve this one).
The stale data message currently talks about Autumn - we've missed this by folding the regular maintenance into the bigger change.
Have adjusted message to reflect this.
=> Update stale data message

www/includes/easyparliament/templates/html/mp/profile.php, www/includes/easyparliament/templates/html/mp/votes.php
Party changed warning is showing because parties being compared incorrectly.
=> Compare slugified parties

www/docs/postcode/index.php, www/includes/easyparliament/templates/html/postcode/ge2024.php
Very basic link to polling station: uses the UPRN if we have it, postcode if we don't.
=> Add WhereDoIVote link

scripts/load-people
Due to changes in https://github.com/mysociety/parlparse/pull/173
=> Use constituency data from main people.json file.

www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
For new memberships, use WMC23: e.g. https://www.localintelligencehub.com/area/WMC23/Carshalton%20and%20Wallington
=> Update LIH link format for new cons

classes/Homepage.php, classes/SectionView/SectionView.php, www/docs/style/sass/app.scss, www/docs/style/sass/layout/_header.scss
I tried decreasing the width to 28% and It works using my name.
=> Homepage and Navbar Improvements

www/docs/style/sass/_mysoc_footer.scss, www/docs/style/sass/pages/_home.scss, www/docs/style/sass/parts/_panels.scss
The first commit should improve the overlapping of the searchbar on the next element.
I also added some other commits to fix the following:
**Spacing problems in the homepage(mobile)**
**Odd border radius on mobile**
**Horizontal spacing on mobile not consistent with the rest of the page**
https://github.com/user-attachments/assets/fc79baf9-f632-4923-ba29-7532a02bf6e8
=> Homepage improvements

www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
Not a bad idea, but also not leading to donations.
Alternative approach might focus on mailing list first - and needs to be more tailored if being the 'main' thing for devolved parliaments.
=> Remove new parliament panel

locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
Some fuzzy terms have snuck in and the test is failing.
=> [alerts] Update welsh terms from fuzzy

classes/Stripe.php, classes/Subscription.php, classes/TestStripe.php, tests/AcceptApiTest.php, www/docs/api/key.php, www/docs/api/update-card.php
release is only available this way, as far as I can see. Left hook.php alone for now though.
=> [Stripe] Convert to using instance calls.

scripts/dailyupdate, src/twfy_tools/utils/personinfo.py
Only suppresses the progress bar for using in cron jobs
=> add suppress-progress option to personinfo import

www/docs/interests/index.php, www/docs/support-us/index.php
=> Open-graph-tweaks

scripts/mpinfoin.pl
Important thing is it fixes the bad if statement introduced by the votes PR.
Building on that, I've made it so the verbose argument works on its own (for debugging).
I've also removed the regmem loader - this was left in for some overlap while the new data was coming in, but now can be removed and speed up the ingest process.
=> Fix-mpinfoin

src/twfy_tools/utils/votes2db.py
We're currently importing the draft policies from votes.theyworkforyou.com.
The other file shouldn't display them in the first place - but we need to adjust the script here so it removes non-present items.
=> Limit imported policies to active policies
