mysociety/theyworkforyou

- classes/SectionView/SectionView.php
if the link from the search page, or more realistically an email goes
through more than one level of redirect then the search term is lost
from it. Check if it's present and add it back in to the redirect.
Note that we will always lose and anchor part of the URL in this process
as that's all dealt with purely client side and never supplied to the
server.
Fixes #754
> retain search term over multiple redirects

- www/includes/wikipedia.php
The previous regular expression could easily run out of stack space when
run on something with a large number of HTML elements. The new one is a)
simpler, b) explained, and c) possessive, so hopefully won't use any.
> Stop regular expression segfault.

- www/includes/easyparliament/templates/html/mp/votes.php
This fixes a bug I introduced when we added regional header images. 
An MP's votes page will now have a background image again
> regional background now appears on MP votes pages

- tests/AcceptApiTest.php
- tests/AcceptBasicTest.php
- tests/AlertsTest.php
- tests/Bootstrap.php
- tests/CommentTest.php
- tests/DivisionsTest.php
- tests/FetchPageTestCase.php
- tests/GlossaryTest.php
- tests/HansardTest.php
- tests/MemberTest.php
- tests/PageTest.php
- tests/PostcodeTest.php
- tests/SearchTest.php
- tests/SectionTest.php
- tests/TWFY_Database_TestCase.php
- tests/UserTest.php
rather than having the same getConnection method in all the database
tests extract it out to an abstract class and inherit from that.
Also move the includes for it and the FetchPage test class to the
bootstrapper so they don't need to be included in every file.
> extract test GetConnection out to abstract class and inherit

- classes/Memcache.php
- classes/Model/Banner.php
- classes/Renderer.php
- db/schema.sql
- tests/PageTest.php
- tests/_fixtures/member.xml
- www/docs/admin/banner.php
- www/docs/mp/index.php
- www/docs/style/sass/layout/_header.scss
- www/includes/easyparliament/member.php
- www/includes/easyparliament/metadata.php
- www/includes/easyparliament/page.php
- www/includes/easyparliament/templates/html/header.php
This adds a banner to pages with the new design.
It also adds an editorial table, which is a key/value thing at the moment in anticipation of it being used for e.g. controlling things on the front page, and fetches the banner text from that. This allows the banner to now be edited in the admin interface rather than having to edit files and deploy the site.
> Banner for new style pages plus move content into database

- db/0003-add-moffice-id.sql
- db/schema.sql
- scripts/load-people
The parlparse JSON no longer has sequential duplicates, so we don't need that slow code any more. Add a date so we don't have to consider old things if we don't want to, and store office ID to save deleting the entire table each run.
> Improve load people

- classes/Member.php
- tests/MemberTest.php
- tests/PageTest.php
- tests/_fixtures/member.xml
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
Note to say they were recently elected which is why there's not much
content on the page. Dissapears either after 6 months or if they've got
recent activity.
Similar for policy page.
Fixes #703
> Add section to new MP's pages saying they are new

- scripts/load-people
Because mysql's default collation is case insensitive the replace into
is triggered by case differences in names becuase the index sees
Berwick-upon-Tweed and Berwick-Upon-Tweed as the same. This means the
for the second one we update main_name to 0 which means no results are
found by the constituency name search.
Fixes #856
> ignore case differences when loading constituencies

- www/docs/style/sass/_twfy-mixins.scss
- www/docs/style/sass/pages/_mp.scss
- www/docs/style/sass/pages/_section.scss
- www/docs/style/sass/pages/_topics.scss
- www/includes/easyparliament/templates/html/mp/divisions.php
- www/includes/easyparliament/templates/html/mp/header.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
- www/includes/easyparliament/templates/html/section/section.php
- www/includes/easyparliament/templates/html/topic/topic.php
Fixes #695.
MP pages and debates pages were using a variety of different methods to set columns and gutters, especially on full-width elements, and each of these methods resulted in a lack of gutters at one breakpoint or another.
This PR standardises all the "new style" pages (MP pages, debates/wrans pages, topic pages) to use the `.full-page__unit` convention, and to avoid nested grid columns. The `/alert/by-postcode` page and [new homepage](https://github.com/mysociety/theyworkforyou/tree/issues/589-new-homepage-design) already use `.full-page__unit` where necessary, so didn't need any fixes.
The template changes *look* more drastic than they really are, because a lot of them are indentation changes as I've added or removed wrapping elements, to keep the same structure across all the …
> Standardise page gutters on "new" pages

- scripts/load-people
- scripts/mpinfoin.pl
- scripts/xml2db.pl
- www/includes/easyparliament/member.php
- www/includes/easyparliament/searchengine.php
This allows us to load in and use people that have been merged without having to update every existing XML file/update all the search indices.
https://github.com/mysociety/theyworkforyou/pull/869/files?w=1 to ignore the whitespace commit.
> Allow spotting of 'redirect' entries

- www/docs/mp/index.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/metadata.php
- www/includes/easyparliament/templates/html/mp/error.php
If someone arrives at /mp without either a session with a postcode or a query string then present them with a postcode lookup dialog and also a link to the appropriate list of representatives for the page type.
> Add postcode search to /mp page if redirect fails

- tests/AlertsPageTest.php
- tests/_fixtures/alertspage.xml
- www/docs/alert/index.php
If someone is signing up for and alert that is of the form
ZZ1 1AA elephants
then it's likely they actually want to sign up for the MP for that
postcode mentioning elephants so put in a notice to this effect and also
a button to enable them to subscribe to an alert for that.
part of #593
> detect signups for postcodes with a keyword and advise user

- www/includes/easyparliament/hansardlist.php
Fix e.g. http://www.theyworkforyou.com/search/?s=speaker:25177&p=2&pop=1 (which should switch to "Bishop of Durham" halfway down.
> Fix changing name on search results

- www/docs/style/sass/pages/_mp.scss
Simple fix for #770.
Makes the MP's constituency white, to improve contrast against the background image.
> Incrase contast for consituency name in MP header

- tests/PageTest.php
- www/includes/easyparliament/templates/html/header.php
Previously if the banner_text page variable was set to anything, even an
empty string, then the banner would be displayed with no content. This
makes sure that we only set the banner_text variable if there is some
banner content.
Fixes #915
> only set banner_text page variable if banner content

- classes/SectionView/SectionView.php
- tests/SearchTest.php
- tests/SectionTest.php
- tests/_fixtures/section.xml
- www/includes/easyparliament/searchengine.php
Because of the way the search engine highlighting works it will add
highlighting to text that is inside tags, e.g. in the title tag of a
glossary link. The glossary highlighting doesn't do this so swap the
order we do these in.
Fixes #912
> swap search term and glossary highlighting order

- classes/PolicyPositions.php
- tests/DivisionsTest.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/templates/html/mp/divisions.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
- www/includes/easyparliament/templates/html/topic/topic.php
- www/includes/utility.php
Connects to #558.
* "Generally", "Almost always", and "Consistently" rather than "Moderately", "Strongly", "Very strongly".
* Explanation of how votes are summarised on topic vote summary page.
* Chunkier buttons next to vote summaries, also reworded from "Details" to "Show votes".
> Improvements to vote summary wording and buttons

- classes/Member.php
- classes/Party.php
- classes/PolicyPositions.php
- db/0007-add-policy-vote-to-divisions.sql
- db/0008-add-party-policy.sql
- db/schema.sql
- scripts/generate_party_positions.php
- scripts/json2db.pl
- tests/PartyTest.php
- tests/_fixtures/party.xml
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
This imports the policy vote from PublicWhip and then uses all the votes of current party members to calculate the party's position on a policy. It then compares that with an MP's position and if it is in opposition then it displays that policy on the MP's profile page.
Connects to #910
> Display any votes where MP differs from party on profile page

- classes/Member.php
- classes/PolicyPositions.php
- scripts/json2db.pl
- tests/DivisionsTest.php
- tests/_fixtures/divisions.xml
- tests/_fixtures/party.xml
- www/includes/easyparliament/templates/html/mp/divisions.php
- www/includes/easyparliament/templates/html/mp/votes.php
When we import the division votes we look at MPs who've voted in strong
divisions and if so set a flag for the current policy accordingly. We
then use this flag to decide if we should say what an MP's position on
an issue is. If they've not voted in a strong division we fall back to
saying we don't have enough information to decide, but still allow users
to see the votes for that policy.
Also, don't include policies without strong votes on the front page or
the differs from party stats.
Fixes #947
> Only display MP policy position if voted in strong division

- www/docs/style/sass/pages/_mp.scss
Fixes #690.
The full complement now looks like:
> Add party colours for UKIP, Plaid Cymru, DUP, and Sinn Féin

- www/includes/data.php
- www/includes/easyparliament/comment.php
- www/includes/easyparliament/commentlist.php
- www/includes/easyparliament/commentreport.php
- www/includes/easyparliament/commentreportlist.php
- www/includes/easyparliament/editqueue.php
- www/includes/easyparliament/glossary.php
- www/includes/easyparliament/init.php
- www/includes/easyparliament/people.php
- www/includes/easyparliament/searchengine.php
- www/includes/easyparliament/searchlog.php
- www/includes/easyparliament/trackback.php
- www/includes/easyparliament/user.php
- www/includes/url.php
Old-style constructors will throw warnings in PHP 7, and will not be supported in PHP 8. This is mostly to keep the build logs free of warnings so we can see what is actually broken.
[Before](https://travis-ci.org/mysociety/theyworkforyou/jobs/76981612) vs [after](https://travis-ci.org/mysociety/theyworkforyou/jobs/76988009).
**NB:** You probably also want to merge the changes in commonlib, since nothing should be running on PHP 4.
> Replace legacy className() constructors with future-proof __construct()

- classes/People.php
Means that when you click on the Download list as CSV link on the people
pages then it downloads a file rather than just spewing out the CSV into
the browser.
Fixes #654
> add content disposition to set filename for person CSV

- www/includes/easyparliament/templates/html/static/privacy.php
Doesn't change any of the intent of the policy (we still collect aggregate data to improve the site, nothing else), but it does allow for us to enable the demographic features in Google Analytics.
It also brings us up to the current guidelines from Google on what we should include in the privacy policy (explicit list of features used, statement from Google, and opt-out information).
Using text from http://www.mysociety.co.uk/about/privacy/.
> Update privacy policy with an improved Google Analytics section

- classes/Search.php
- classes/Search/Normal.php
The advanced search terms weren't registered as session vars for the search page so the URL constructor was throwing them away.
Fixes #956
> Advanced search terms lost on pagination links

- www/docs/style/sass/app.scss
The line-height for H1's feel a bit too loose when wrapped.
This sets a 1.15em rule in app.scss
> amends h1 line-height

- scripts/mpinfoin.pl
Sometimes the first contribution someone makes is an oral question,
prior to their official maiden speech. Make sure the first item we take
includes a common maiden speech phrase.
> Improve maiden speech link by looking for words.

- www/docs/style/sass/pages/_home.scss
- www/includes/easyparliament/templates/html/index.php
- www/includes/easyparliament/templates/html/ni/index.php
- www/includes/easyparliament/templates/html/scotland/index.php
Fixes #887.
Pretty uncontentious changes. Sorts out the weird vertical spacing in the "Upcoming" section on the homepage, and also unfolds the "Recently" section so that all the items are shown on pageload, which has the benefit of evening up the length of that section with the "Upcoming" one next to it.
@dracos could you check this works locally for you? I don't have enough data in my VM to fill the Recently and Upcoming sections.
> Homepage spacing tweaks

- www/docs/style/sass/pages/_static.scss
Fixes #921.
A really minimal fix that sets a hard limit for the length of lines on `.static-page` pages.
It's still a *bit* wide, but reducing it further would mean doing extra work to stop the headings wrapping etc. This is a good compromise, and much easier to read than the full width lines that are there now.
> Limit line lengths on static pages

- www/docs/wales/index.php
- www/includes/easyparliament/templates/html/wales/index.php
As spotted by @droom in #1003 – the "Wales" page was pretty poor, considering its position in the country switcher effectively makes it a top level page.
So this gives it a layout in keeping with the other national assembly sections.
> Make Wales page look less of an afterthought

- classes/Party.php
- tests/PartyTest.php
- tests/_fixtures/party.xml
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
Add a getCurrentMemberCount method to party class and use that to check
if a party has only one member, and if so do not print a differs
from/votes the same as bit.
Fixes #1019
> Fix party stance text for single member parties

- www/docs/style/sass/_print.scss
- www/docs/style/sass/app.scss
Interactive elements like search boxes and buttons are hidden. Floated columns/sidebars are unfloated, and section padding is removed. Plus a bunch of other small improvements.
Fixes #892.
Here are a few example pages, from different browsers. If you can spot something that's been removed and shouldn't have been, or something that still needs to change, leave a comment.
> Improve printed output

- www/docs/style/sass/pages/_static.scss
Fixes #1009.
Not pretty, but it's better than before.
> Stop imposing max-width to limit lines on legacy pages

- www/docs/style/sass/pages/_search.scss
- www/includes/easyparliament/templates/html/search/by-person.php
- www/includes/easyparliament/templates/html/search/form_main.php
- www/includes/easyparliament/templates/html/search/form_options.php
- www/includes/easyparliament/templates/html/search/results.php
Fixes #1001.
The FOUC is basically fixed by just the addition of [these 4 lines of CSS](https://github.com/mysociety/theyworkforyou/blob/7f6f1ae0e5de03ab4c2e51c01c2690e01dcf6932/www/docs/style/sass/pages/_search.scss#L64-L66) and the removal of [this line of JavaScript](https://github.com/mysociety/theyworkforyou/commit/898e27481ef40db92be5efbd9cd754a409821002#diff-96906dac833d9062f945ce65fb284a39L157).
But we also took the opportunity to improve the UX for users without JavaScript enabled (moving the advanced search inputs to the end of the page by default), and to tidy up the indentation in the search templates.
Unlike https://github.com/mysociety/theyworkforyou/issues/1034, there is no way for non-javascript users to show and hide the advanced options – they are just *always* visible …
> Avoid advanced search options flash on page load

- www/includes/easyparliament/page.php
Avoids odd encoding issues when the user's OS is set to a different
encoding.
Fixes #1033
> force annotation form to upload ISO-8859-1

- classes/Renderer/Header.php
- www/docs/style/sass/layout/_header.scss
- www/includes/easyparliament/metadata.php
Fixes #1053.
Nav text is now 16px rather than 18px, to make room for the extra menu item.
> Add Contact link to main nav

- classes/Member.php
- scripts/mpinfoin.pl
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
Replace the WTT stats banner with one that displays how an MP campaigned in the EU referendum along with a link to contact your MP using WTT. If the page is for the user's MP then we link directly to that page on WTT, otherwise the front page.
Uses the BBC's data on how MP's campaigned/stood in the EU referendum.
Fixes #1112
> WIP display MP's EU referendum stance on profile page

- classes/Search.php
The URL creation already pulls in the search string so we don't need to
re-add it, especially as doing so means on the next page the pid is
added again.
Fixes #1105
> stop duplication of speaker: part of search strings

- README.md
Browserstack gives us free cross-browser / cross-device testing, in exchange for an acknowledgement in the README of projects for which we use it.
I just noticed, the TheyWorkForYou README is missing the acknowledgement.
> Acknowledge browserstack in README

- classes/Member.php
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
Instead of explaining why we don't have expenses for an MP just link to
the information. Also fix it so we only link to the relevant
information.
Fixes #313
> remove expenses explantion and just show links

- www/docs/api/index.php
People often assume MPs' email addresses are available via the API, but they are not. Add text explaining this and sending them to EveryPolitician, where they can get that data (and loads more).
> Add link to EveryPolitician

- classes/Renderer.php
- classes/Search/ParseArgs.php
- scripts/daily-api-usage.php
- scripts/future-fetch.py
- scripts/json2db.pl
- scripts/load-people
- scripts/mpinfoin.pl
- scripts/mprss.php
- scripts/xml2db.pl
- tests/CommentTest.php
- www/docs/api/api_functions.php
- www/docs/api/api_getGeometry.php
- www/docs/down.default.html
- www/docs/news/rdf.php
- www/includes/easyparliament/page.php
- www/includes/easyparliament/searchengine.php
- www/includes/easyparliament/templates/html/header.php
- www/includes/easyparliament/templates/rss/hansard_search.php
- www/includes/easyparliament/trackback.php
- www/includes/mysql.php
- www/includes/utility.php
This updates the site to output and store UTF-8 everywhere rather than ISO-8859-1.
Along with this branch the following changes will need to be made to the database:
```sql
ALTER database twfy default character set utf8mb4;
ALTER database twfy default collate utf8mb4_general_ci;
```
and then something like this for all the tables:
```sql
ALTER table member convert to character set utf8mb4;
```
This latter command also updates the collation on columns for those where we have overridden it.
Generate this for all table with:
```bash
#!/bin/bash
QUERY="select table_name from information_schema.TABLES T, information_schema.         COLLATION_CHARACTER_SET_APPLICABILITY CCSA WHERE character_set_name =         'latin1' AND CCSA.collation_name = T.table_collation AND T.table_schema = …
```
> Update TWFY to use UTF-8

- www/includes/easyparliament/searchengine.php
This appears to fix #1206 and fix #1208 – but I do not understand why I switched away from the translation table to the current behaviour in 2f9d9f1e35b8483aa467b53b85b17b3a6afb95d7 which is somewhat worrying… (search results do *appear* to still be working with this change, so that commit message is not helpful).
> Use translation table rather than chr().

- tests/AcceptApiTest.php
- tests/_fixtures/api.xml
- www/docs/api/api_functions.php
otherwise iconv will convert them into plain quotes and hence break the
JS output.
Fixes #1218
> escape utf8 fancy quotes from js api output

- scripts/mpinfoin.pl
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
This uses the XML generated by parlparse from EveryPolitician to update the twitter and facebook links in `person_info`. It also splits these out to a Social Media sub-heading in the profile to make them a bit more obvious.
Part of #1133
> Add social media details from EP

- conf/general-example
- scripts/morningupdate
- search/index.pl
Provides required support for Xapian Replication.
- Provides for setting `XAPIAN_MAX_CHANGESETS` in `conf/general` and uses export this into the environment within `search/index.pl` if present. This ensures it is set wherever the index script is called from.
- Supplies necessary scripts to integrate trigger replication from the client-side based on those used with Alaveteli.
Once this is merged, we activate by setting a values for the various new configuration variables in the config file. See also https://github.com/mysociety/sysadmin/issues/654.
> Add support for Xapian Replication (resolves #1167)

- www/includes/easyparliament/templates/html/people/index.php
This fixes the A-Z links so they refer to first names when sorting by first name.
It hides the A-Z links when sorting by party as they aren't actually useful in that case.
Fixes #1060
> Fix A-Z links on MP list page for non last name sorting

- www/includes/easyparliament/templates/html/people/index.php
- www/includes/easyparliament/templates/html/section/_section_content.php
Improve the merging of run-on paragraphs to detect when something looks
like the end of a quote from the official record by checking for a
paragraph ending with ]. This avoids formatting a follow on sentence
into the indent for the quote.
Fixes #1195
> do not merge paragraphs after a quote from official record

- classes/Member.php
- classes/Search/Normal.php
- www/docs/mp/index.php
- www/includes/easyparliament/member.php
- www/includes/easyparliament/templates/html/mp/header.php
- www/includes/utility.php
This fixes #1056, and starts on #1055 (it does a search of any office positions ordered by from date descending, so you now get too much and it doesn't push exact matches to the top, so JH is at least there, but fifth).
> Better position in header; searching of offices

- scripts/mpinfoin.pl
- www/docs/regmem/index.php
This fixes the broken pound signs on this page.
Fixes #1057
> Encode output on Register of Members' Interests page as UTF-8

- scripts/mpinfoin.pl
Parse all existing regmem files in chronological order so that we have the last entry for all MPs instead of just those with entries in the the latest file. This means we will display the last entry in the Register for former MPs on their profile page.
Fixes #1243
> Parse all Register of Members' Interest files

- www/docs/js/main.js
- www/docs/mp/index.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/templates/html/mp/votes.php
It's not possible to subscribe to share events using FB.Event so roll
our own code to launch the share dialog using FB.ui. This means we can
hook in Google Analytics to the response handler.
Fixes #1238
> custom Facebook share button for tracking MP voting record shares

- .travis.yml
- classes/Memcache.php
Makes the necessary changes to get tests passing on PHP 7 on Travis, more specifically:
* Do not attempt to overload `random_bytes()` if the function already exists.
* Conditionally use `memcached.so` instead of `memcache.so` on PHP 7 in Travis configuration.
* The `TWFY\Memcache` class now detects the presence of `\Memcached` and uses that (with appropriate syntax changes) where necessary.
> WIP: Get tests passing on PHP7

- .gitmodules
- composer.json
- composer.lock
Swaps out loading the Facebook SDK via git submodule to using Composer and Packagist instead.
> Move Facebook SDK to use Packagist/Composer

- www/docs/api/index.php
The email address quoted on this page gets email from a number of different sources, but people who find it via this page don't know that, so they quite often don't say what they're emailing about (assuming we'll know). Hopefully if we add a request to mention TWFY it'll reduce the headscratching and need for detective work when emails come in...
> Add instruction to mention TWFY when emailing

- Vagrantfile
No idea why this is needed, but without it, whenever I start the VM and SSH in, Apache isn’t running, so I have to run it manually.
I’ve had this fix hanging around, unstaged, in my git directory for months. Figured I should finally see whether we want to merge it into `master` 😉
> Restart Apache when booting Vagrant VM

- www/includes/easyparliament/templates/html/search/by-person.php
A user wrote in to say "I have followed the instructions however there is not a button named “I want to write to this Lord” as described." and was right, there isn't. This commit changes the instructions to refer to what's actually on the page (which changed, I presume, in a long-ago redesign).
> Remove reference to a non-existent button

- www/docs/style/sass/pages/_divisions.scss
- www/includes/easyparliament/templates/html/section/_section_content.php
- www/includes/easyparliament/templates/html/section/_section_toc.php
- www/includes/easyparliament/templates/html/section/section.php
This adds a vote-contents list to the top of a debate page. If the vote has manual yes/no descriptions, they are also included, otherwise it will only be a list of division numbers.
Fixes #1201.
> Put links to any divisions at top of debate page.

- www/docs/style/config.rb
This specifies a default encoding for stylesheets as UTF-8, which makes Compass happier in Vagrant boxes.
> Specify default encoding for stylesheets.

- www/includes/easyparliament/templates/html/mp/votes.php
It is nice that easily-shareable screenshots of an MP's voting record are available, but at the moment they're hard to get at; they're set up to be automatically used when shared on social media (through the `og:image` meta element) but it may be useful to allow people to get at those images directly so they can copy them to share in other places (for example, pasting them into chat apps, or sharing on social media without having to use the provided "share" buttons). So, make the word "screenshot" a link to that screenshot explicitly so it can be got at.
> Link directly to screenshot of votes

- www/includes/easyparliament/member.php
Adding missing string for new ENUM value of "recall_petition"
> Plain-English versions of left_reason don't include entry for new value "recall_petition"

- www/includes/easyparliament/templates/emails/alert_gone.txt
- www/includes/easyparliament/templates/emails/alert_mailout.txt
- www/includes/easyparliament/templates/emails/alert_new_mp.txt
TWFY alert donate link doesn't current include campaign tracking information. 
This replaces the link with a redirect that introduces tracking information.
Addresses https://github.com/mysociety/theyworkforyou/issues/1388.
> Replaced email alert donate link

- Vagrantfile
- bin/install-php7-xapian.sh
This adds backports to the apt sources in the Vagrant box and builds the PHP Xapian bindings for the corresponding Xapian version.
> Update Vagrant box to use Xapian 1.4.9

- www/docs/js/main.js
- www/includes/easyparliament/templates/html/header.php
- www/includes/easyparliament/templates/html/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
Up until Thursday, the banners will say "only X days to go" (see screenshots below). On Thursday, they’ll say "only 1 day to go". On Friday, they’ll say "only a few hours to go", until 10:00, when they’ll say "only an hour to go".
After 12:00, all the banners will be hidden.
Fixes https://github.com/mysociety/theyworkforyou/issues/1493.
> Update crowfunder banners during and after crowdfunder

- www/includes/easyparliament/templates/html/mp/divisions.php
Resolves #1488 
Updates URL parameter from amp (which is not currently a valid parameter and so is disregarded) to dmp (which restricts results to a specific policy).
> Correct broken policy link

- classes/Renderer/Footer.php
- www/includes/easyparliament/metadata.php
- www/includes/easyparliament/templates/html/header.php
Resolves #1465 
Removal of defunct theyworkforyou.co.nz site
> Remove New Zealand website links

- www/docs/api/api_functions.php
- www/docs/api/cancel-plan.php
- www/docs/api/index.php
- www/docs/api/key.php
- www/docs/api/update-plan.php
We get more email than I'd like from people who can't figure out how to manage, change, cancel their subscription. This might help them find the page?
> Add hint about where to manage your API account

- classes/Member.php
- tests/VotesTest.php
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/_vote_description.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
Fixes #1512.
Includes the same information as is shown on the main MP page (where one score <0.4 and other is >0.6), but also includes differences where one score is between 0.4 and 0.6 and other score is outside that range (so one is 'mixed' and other is not mixed). Thoughts welcome.
Tried to tidy up a bit too, having the diffs include the information they need rather than setting the policies/party_positions globals.
> Add party voting line to MP votes page.

- www/includes/easyparliament/metadata.php
Title tags for the 'Sign in' and 'Join' links in the main menu still talk about annotations as the reason/purpose you might want to have a TWFY account. Annotation functionality was removed a while back. This changes the wording to refer to email alerts instead.
> Remove some more references to annotations

- classes/Member.php
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
The overview page for a live party-switcher now contains language talking about their current and comparison party. 
The voting record page when comparing the current party to the comparison party puts the current party now compared to a version of the current party that merges labour/coop and labour.
> Improve party-switch description

- www/includes/easyparliament/templates/emails/alert_mailout.html
- www/includes/easyparliament/templates/emails/alert_mailout.txt
This adds a link to an alchemer survey to the text and html alerts template.
> Add link to professional use survey to email alerts

- .github/workflows/mirror.yml
Buster update required update to action-git-pusher (https://github.com/mysociety/action-git-pusher/pull/2)
Increment version to new v1.1.1 tag.
> Update mirror action

- .devcontainer/auto-quick-setup/devcontainer.json
- .github/workflows/mirror.yml
- README.md
- classes/PartyCohort.php
- scripts/json2db.pl
- scripts/load-people
- scripts/mpinfoin.pl
- scripts/quick-populate
This PR adjusts data loading scripts to be quicker for loading initial sets of data, and creates a new `script/quick-populate` to make loading a minimal set of data consisutent.
This replaces https://github.com/mysociety/theyworkforyou/pull/1591 because that was merging into an outdated version of a branch that has now been merged into master.
I have adjusted the populate scripts based on the feedback in that PR request.
> Auto populate script

- tests/AcceptBasicTest.php
- www/docs/style/sass/pages/_home.scss
- www/includes/easyparliament/templates/html/footer.php
- www/includes/easyparliament/templates/html/index.php
- www/includes/easyparliament/templates/html/london/index.php
- www/includes/easyparliament/templates/html/ni/index.php
- www/includes/easyparliament/templates/html/scotland/index.php
- www/includes/easyparliament/templates/html/static/about.php
- www/includes/easyparliament/templates/html/wales/index.php
This PR does the following quick changes:
- A quick change to simplify the home page copy
- A quick fix for colour contrast on homepage
- Placeholder text for Welsh Parliament (given about page talks about "across all parliaments" and this will be true soon).
- A new version of the about page.
My general approach here is to make an improvement we can come back to later rather than trying to get it perfect now.
Questions:
- @MyfanwyNixon : This copy look ok enough? (with a view we'll want to come back and change later in the year as we get the repowering democracy work up).
- @zarino: Can you live with this as a temporary approach to the contrast issue (a lighter green background). Would still love a proper pass (https://github.com/mysociety/Design-Internal-tasks/issues/7) at some point …
> Change copy on front pages and about page

- www/docs/style/sass/_twfy-mixins.scss
There's a margin that offsets the text in text boxes, which does this to the search:
Removing the line fixes it:
Looks like it was added a few years ago to add spacing on user sign up page - but this seems a worse problem that that.
> Remove top margin on form controls

- classes/Policies.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/templates/html/mp/_covid19_panel.php
- www/includes/easyparliament/templates/html/mp/_division_description.php
- www/includes/easyparliament/templates/html/mp/_vote_description.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/recent.php
- www/includes/easyparliament/templates/html/mp/votes.php
- Covid messaging moved to bottom to be linked to rather than at the top of all the pages.
- Removed from profile page altogether
- Absences for votes in early June 2020 have extra text.
- Policies with a vote in that time have extra text (only 1 for now, one more in new policies)
> Remove blanket covid text in favour of highlighting specific votes.

- www/docs/js/main.js
- www/includes/easyparliament/templates/html/footer.php
- www/includes/easyparliament/templates/html/header.php
- www/includes/easyparliament/templates/html/mp/header.php
- www/includes/easyparliament/templates/html/mp/profile.php
Uses the cookieless GA4 approach described in https://docs.google.com/document/d/1ZXbkXoLE0eLnUWJaVv_8xpnVOlOHGCxPP_Uo7cfoFJo/edit
- Adds GA4 config
- monkey-patches `document.cookies` to prevent ga setting cookies.
This PR originally used the measurement protocol - but those commits will come out in a final squish.
> GA4 analytics

- classes/AlertView/Standard.php
- classes/User.php
- locale/TheyWorkForYou.pot
- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- www/docs/user/login/index.php
- www/docs/user/password/index.php
Finishes off a few translations that appear as validation errors in the standard alert and user sign-up forms ("enter your email", etc).
> [Wales] Translate the standard form error messages

- classes/Renderer/Header.php
- locale/TheyWorkForYou.pot
- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- scripts/quick-populate
- www/docs/style/sass/pages/_home.scss
- www/includes/easyparliament/metadata.php
- www/includes/easyparliament/templates/html/homepage/devolved-list.php
- www/includes/easyparliament/templates/html/index.php
- www/includes/easyparliament/templates/html/ni/index.php
- www/includes/easyparliament/templates/html/scotland/index.php
- www/includes/easyparliament/templates/html/section/_ni_desc.php
- www/includes/easyparliament/templates/html/section/ni_index.php
- www/includes/easyparliament/templates/html/section/senedd_index.php
- www/includes/easyparliament/templates/html/senedd/index.php
London excluded for moment because it needs some sorting out.
Because these are general pages, they don't have the devolved parliament in their parent tree.
This adds additional checks to see if the alert is linked to a specific person, or the search is limited to a particular parliament, and changes the top bar:
> Devolved navigation

- www/docs/api/index.php
- www/includes/easyparliament/templates/html/static/help.php
Should hopefully cut down on some user support questions.
Fixes #1730
> add pointers to raw data from API help and FAQ

- classes/Divisions.php
- tests/DivisionsTest.php
- www/docs/js/main.js
- www/docs/mp/index.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/templates/html/mp/_division_description.php
- www/includes/easyparliament/templates/html/mp/divisions.php
- www/includes/easyparliament/templates/html/mp/recent.php
Fixes #1744 and #1745. Differences from the draft branch:
* Changed Divisions class to always have access to full set of Policies (seemed needless to restrict this);
* Got rid of more knock-on unneeded code (anything to do with weak_count or the JS for that button);
* Changed related_policies to be a two-entry array of array rather than separate two-entry arrays;
* reduced number of close/open PHP blocks a bit.
> Minor changes to division display

- classes/Renderer/User.php
This PR:
* Adds a link to the mySociety donate page in the top bar.
* Moved the language selector to the top right (https://github.com/mysociety/theyworkforyou/issues/1727)
Doesn't entirely solve #1727 because of it doesn't change the hamburger approach.
Donate approach is a bit hacky - didn't want to add it to the metadata file because it's not a page. Is weird to have an external link in the normal navigation - but it's how we've got things set up at the moment.
> Donate and language switch in top bar nav

- bin/docker-entrypoint.sh
- conf/general-example
- docker-compose.yml
Some of the prepopulate scripts depend on having the variable set, but at the moment we're not storing it in the config because it's not the final URL.
This passes through a variable from codespaces secrets to the docker container, and to the php config, which lets the prebuild process gather all the data needed.
(In principle the url will then be available through the prebuild - but as it's not secret secret this is fine)
> Add TWFY_VOTES_URL to docker config

- classes/Member.php
Now elected under another party, use most recent party rather than oldest.
This will compare him to respect (so a small party that doesn't get comparisons) rather than Labour.
In general having a broad rule about the party you're elected under being the primary might be good - but also being able to show all the possible comparisons through twfy-votes gives a better fall back in future.
> Change Galloway comparison party

- Dockerfile
- www/docs/fcgi/php-basic
This reverts commit e47a27dbddc8a2eb5607b235f846c8ccca0534ab.
We're testing the deploy on Bullseye again.
> Revert "Move back to Debian Buster and PHP 7.3"

- www/includes/easyparliament/templates/html/mp/profile.php
If rebellion rate isn't loaded you just get this:
> Fix loose name appearing on voting records

- classes/Renderer/Header.php
- locale/TheyWorkForYou.pot
- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- www/docs/divisions/index.php
- www/includes/easyparliament/metadata.php
- www/includes/easyparliament/templates/html/divisions/index.php
- www/includes/easyparliament/templates/html/homepage/devolved-list.php
@dracos made it possible to filter the recent votes screen by chamber.
This PR solidifies this a bit - adding chamber specific links to the menus, and more specific descriptions. to the page
Using multiple at once should still work fine as it as before. 
E.g. the Senedd:
> Improved division linking

- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
- www/includes/easyparliament/templates/html/mp/_person_navigation.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/recent.php
- www/includes/easyparliament/templates/html/mp/votes.php
As we've now moved the voting summary out of the main page, we want something to take its place when people get to the MP page after entering their postcode. 
This introduces a basic "intro to your MP" page, that we can expand later - basic links to other mySociety services. 
This also switches around the profile and the recent appearances - ideally we'd be moving the recent appearance into its own tab - so that it's a bit towards for the bottom for the moment is fine.  More aspects of the profile might move into the  'intro' paragraph. 
This menu is now shared between the various views - being clearer about the logic of what is and isn't included for different kinds of representative rather than this being implicit in who did or didn't have various options enabled. 
Technically not …
> Update summary page

- .gitignore
- bin/deploy.bash
- bin/docker-entrypoint.sh
- conf/general-example
- conf/packages
- db/0023-add-division-title-priority.sql
- db/schema.sql
- docker-compose.yml
- requirements.txt
- scripts/division_io.py
- scripts/morningupdate
This PR adds `division_io.py` - a click CLI to handle importing and exporting division data.
This handles bulk importing updates to division titles (e.g. from Parliament's commons votes api), and exporting parquet tables of divisions as a basic api to feed twfy-votes.
There is an adjustment to the division table schema - adding a `title_priority` field. This is to keep track of the origin of the current title, and stop manual updates to titles being overridden by automated ones. Existing titles with a `yes_text` are retrospectively updated in priority. 
For the moment, this uses a requirements.txt file for the needed python packages. When the server is updated, I'll do a new PR to tidy up the python-tooling in general.  Unsure for the moment if this needs the morningupdate commands to run …
> Division title importer/exporter

- .github/workflows/default.yml
- classes/Divisions.php
- classes/Policies.php
- markdown/voting-information.md
- scripts/mpinfoin.pl
- www/docs/mp/index.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/member.php
- www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
- www/includes/easyparliament/templates/html/mp/_cross_party_mp_panel.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/votes.php
Series of small fixups and tidy-ups - I don't think anything controversial.
> Voting copy tweaks

- www/includes/easyparliament/templates/html/mp/votes.php
Our party explanation dialogue works for former MPs, but is turned off: this enables that.
Originally this was because the comparison system was *only* for current MPs, but it's been independent of that for a few years.
> Show party explanation for former MPs

- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- www/docs/postcode/index.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/templates/html/postcode/index.php
Expands approach to cover devolved reps when we have photos.
> Add images to all reps on postcode page

- conf/httpd.conf
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
- www/includes/easyparliament/templates/html/mp/_person_navigation.php
- www/includes/easyparliament/templates/html/mp/_profile_footer.php
- www/includes/easyparliament/templates/html/mp/divisions.php
- www/includes/easyparliament/templates/html/mp/profile.php
- www/includes/easyparliament/templates/html/mp/recent.php
- www/includes/easyparliament/templates/html/mp/register.php
- www/includes/easyparliament/templates/html/mp/votes.php
Move register of interests to separate sub profile page.
- Clearer top navigation from overview page (We should do the same to debates at some point)
- Track interest in this feature
- More room for text about whofundsthem. 
Room for improving this with new boilerplate text - but this does a few things quickly. 
As we want to do this with recent debates/future features(!?) i've moved the list of allowed sub-profile pages from httpd.conf into the profile php page to have more of the logic in one place. But we add new features rarely enough if the other approach is better for some reason can switch back.
> Separate register page

- www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
- www/includes/easyparliament/templates/html/postcode/ge2024.php
- www/includes/easyparliament/templates/html/postcode/index.php
Editing pass updating the copy on postcode and MP page linking to more resources.
Trying putting the election box beneath the former MP box to make the navigation a bit clearer at the top. I think the election box is still fairly clear (especially as now a bit bigger with more buttons).
> Election copy changes

- .github/workflows/mirror.yml
A tidy up for my github based workflow. This PR adds a manual option to the mirror action to force push a branch back to git.mysociety.org. The default is still that git.mysociety.org takes priority. 
This works as expected in the twfy-votes repo. 
Reasoning:
Because git.mysociety.org is the primary, if I rewrite the history in a branch, to get that into git.mysociety.org I need to open up a local theyworkforyou, pull from one, and force push to the other. This moves that into a few buttons on github - while not being an automatic process.
> Add force option to mirror action

- classes/Homepage.php
- markdown/post-election.md
- www/docs/postcode/index.php
- www/includes/easyparliament/templates/html/index.php
- www/includes/easyparliament/templates/html/postcode/ge2024-post-election.php
- www/includes/easyparliament/templates/html/postcode/index.php
After 10pm, switches to this view on the candidates page, and change homepage text.
(Text may be tweaked slightly but wanted to get approval on basic approach and the form)
> Post election

- classes/Renderer/Header.php
We've currently got a few parts of the site that haven't updated in a long period of time. The London section it out of date for members and questions, and Scottish written questions doesn't work. 
We have plans to fix these in months - but for the moment I want to hide these from the top navigation so if we made more noise about our devolved content, we don't get a "hang on, this bits been broken since 2011".
> Remove some items from top navigation

- scripts/division_io.py
Adjusts the export for twfy-votes to more closely mirror the original public whip data table dumps.
> Update queries to better match pw export

- www/docs/style/sass/app.scss
- www/docs/style/sass/pages/_business.scss
- www/docs/style/sass/pages/_search.scss
- www/docs/style/sass/parts/_sidebar_right.scss
- www/includes/easyparliament/templates/html/announcements/_sidebar_right_announcements.php
- www/includes/easyparliament/templates/html/divisions/index.php
- www/includes/easyparliament/templates/html/people/index.php
- www/includes/easyparliament/templates/html/section/_business_section.php
Fixes part of: https://github.com/mysociety/theyworkforyou/issues/1780
> Added right sidebar for donations and subscriptions

- classes/Common.php
- classes/Homepage.php
- www/includes/easyparliament/searchlog.php
Ok, this is adding a few more parameters to the recent searches option.
I've added explicitly some things that were loosely managed through the search caching. 
- Explicit number of IP addresses required to hit the threshold for inclusion. 
- Reduce number of items listed to 5.
- Easier to add exclusions.
Ideally, we'd be able to add exclusions through the admin interface - but this means just adding to an array if we need to make a change. 
In the interest of getting it back up - I've stopped halfway through adding it back to the devolved homepages. 
There is now support for limiting by section - so Scotland could just show Scottish searches. This works fine - but where it needs more work is pulling out when searches for people are devolved politicians (and given the lower daily search …
> Re-enable popular searches

- classes/Stripe.php
- classes/Subscription.php
- classes/TestStripe.php
- composer.json
- composer.lock
- conf/general-example
- www/docs/api/cancel-plan.php
- www/docs/api/hook.php
- www/docs/api/key.php
- www/docs/api/update-card.php
- www/docs/js/payment.js
- www/includes/easyparliament/templates/html/api/check.php
- www/includes/easyparliament/templates/html/api/subscription_detail.php
- www/includes/easyparliament/templates/html/api/update.php
- www/includes/easyparliament/templates/html/donate/_stripe_donate.php
Similar (hopefully identical?) to https://github.com/mysociety/mapit.mysociety.org/pull/158
so we can get on current Stripe API version, and improve downgrade behaviour.
> Upgrade Stripe library/API version to current

- www/docs/style/sass/pages/_business.scss
Fixes: https://github.com/mysociety/theyworkforyou/issues/1833
https://github.com/user-attachments/assets/29b09377-c00a-4383-b489-85ed8a505e9e
Just in case the "Green one" is the active day
> Improved day links accessibility for calendar component

- www/docs/style/sass/_twfy-mixins.scss
Fixes: `button--negative` didn't had a low contrast ratio.
> Improved accessibility for button--negative

- bin/docker-entrypoint.sh
- conf/general-example
- docker-compose.yml
- www/includes/utility.php
This updates the utility class to use the configured smarthost, plus adds a port configuration, and then updates docker to use mailhog and configure php to use this. Largely to make testing things like alert signups etc easier in docker.
> use configured smarthost for PHP emails

- scripts/division_io.py
Joining with the other tables to map GIDs to debates loses the (few, but all relevant to policies) - pre 2004 votes. 
As a result, doing a union with just the divisions in there with no GID.
> Export debates without GID

- www/docs/style/sass/pages/_mp.scss
The new regmem data has more markup for formatting, which is good because we're also dumping a lot more data into the display now.
This is a first pass at styling that data to make the structure (especially of parent/child items - which are new)- clearer.
> Add basic formatting to new regmem data

- scripts/alertmailer.php
- www/includes/easyparliament/templates/emails/alert_mailout.html
If an announcement has a location of 'alerts' then include that at the top of all alerts. The HTML version either uses "Read more" or the `button_text` property for the link.
Announcements are added at the top of the alerts.
Part of #1825
> enable using announcements to add content to alerts

- classes/DataClass/BaseCollection.php
- classes/DataClass/BaseInterface.php
- classes/DataClass/BaseModel.php
- classes/DataClass/Regmem/Annotation.php
- classes/DataClass/Regmem/AnnotationList.php
- classes/DataClass/Regmem/Category.php
- classes/DataClass/Regmem/CategoryList.php
- classes/DataClass/Regmem/Detail.php
- classes/DataClass/Regmem/DetailGroup.php
- classes/DataClass/Regmem/DetailGroupList.php
- classes/DataClass/Regmem/EntryList.php
- classes/DataClass/Regmem/InfoEntry.php
- classes/DataClass/Regmem/Person.php
- classes/DataClass/Regmem/PersonList.php
- classes/DataClass/Regmem/Register.php
- composer.json
- composer.lock
- poetry.lock
- pyproject.toml
- scripts/dailyupdate
- scripts/personinfo
- src/twfy_tools/db/models.py
- src/twfy_tools/db/utils.py
- src/twfy_tools/utils/personinfo.py
- www/docs/mp/index.php
- www/docs/regmem/index.php
- www/includes/easyparliament/templates/html/mp/_person_navigation.php
- www/includes/easyparliament/templates/html/mp/_register_entry.php
- www/includes/easyparliament/templates/html/mp/_register_field.php
- www/includes/easyparliament/templates/html/mp/register.php
This adds devolved registers of interest to TheyWorkForYou (using data from https://github.com/mysociety/parlparse/pull/201)
For this PR, the important bit is getting the data structure and loaders merged - because that's also used for the election summaries. When this is approved I'll comment out the non-commons chambers until we're ready to launch.  This will also need some changes to the text to link to right spreadsheets.
The end goal of this PR is getting the template logic into TWFY rather than being stored in parlparse and the importer, but there's a few steps needed to get there.
- This adds a new personinfo importer - as a way of loading validated data in via python. This dumps json in the personinfo table.
- Inside PHP, this is expanded into dataclasses using the same schema …
> Devolved regmem

- conf/general-example
- scripts/division_io.py
- scripts/json2db.pl
- scripts/morningupdate
- www/includes/easyparliament/templates/html/mp/divisions.php
- www/includes/easyparliament/templates/html/mp/votes.php
This is a basic PR to connect to the new votes site rather than the prototype one. 
Two changes:
- Some adjustments to fields in the output of the new data.
- After divisions are exported, it sends a message to the votes site to import the past days data. 
This needs the config updated to the new votes site, the updater will say something but not fail if the refresh token isn't present.
> Twfy votes connections

- classes/DataClass/Regmem/Annotation.php
- classes/DataClass/Regmem/Category.php
- classes/DataClass/Regmem/CategoryList.php
- classes/DataClass/Regmem/Detail.php
- classes/DataClass/Regmem/HasChamber.php
- classes/DataClass/Regmem/InfoEntry.php
- classes/DataClass/Regmem/Person.php
- classes/DataClass/Regmem/Register.php
- classes/Renderer/Header.php
- locale/TheyWorkForYou.pot
- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- markdown/interests_home.md
- scripts/quick-populate
- www/docs/interests/category.php
- www/docs/mp/index.php
- www/docs/regmem/index.php
- www/includes/easyparliament/metadata.php
- www/includes/easyparliament/templates/html/homepage/devolved-list.php
- www/includes/easyparliament/templates/html/interests/_register_entry.php
- www/includes/easyparliament/templates/html/interests/category.php
- www/includes/easyparliament/templates/html/mp/register.php
This is the PR to make live the devolved register changes - tidying up non gettext features for wales and adding a by category view feature.
Notes:
- I've marked up the text and will put in a translation request. (have just noted i missed marking up on the time comparision page, but have submitted the relevant text).
- The category page works by loading the latest json. This needed a few extra defaults adding to the data structure (the python loader for the regmem data adds the defaults before storing in the database).
- There's a asymmetry in the devolved parliaments have a menu link *direct* to the category page, while the UK wide one goes to the general explainer page. I'm ok with this because that page has details I want from the main heading. 
- Welsh language version looks fine - as …
> Devolved register launch

- scripts/json2db.pl
The `classes/Policies.php` code expects the `scrapedjson/policies.json` file to contain certain keys, however if the [twfy-votes active/all.json](https://votes.theyworkforyou.com/policies/commons/active/all.json) didn't contain a `groups` key then the `set_descs` and `sets` keys in `scrapedjson/policies.json` weren't getting set.
This was the code that was causing an error when the `set_descs` and `sets` key were missing from `scrapedjson/policies.json`.
https://github.com/mysociety/theyworkforyou/blob/9c33051d28c804837dc1c2b958b4c6eb6a5672d8/classes/Policies.php#L68-L77
This change ensures that the expected keys are always set in policies.json, regardless of the input JSON.
Related to https://github.com/mysociety/twfy-votes-django/issues/46
> Ensure policies JSON always has expected keys

- classes/DataClass/Regmem/Register.php
- www/docs/interests/category.php
- www/includes/easyparliament/templates/html/interests/category.php
If someone puts a bad value in the chamber arg then throw a 404, otherwise carry on throwing a 500 so we are warned if expected registers aren't there.
> improve handling of missing/bad registers

- classes/Renderer/Markdown.php
- markdown/support-us.md
- www/docs/js/main.js
- www/docs/support-us/index.php
- www/includes/easyparliament/templates/html/donate/_stripe_donate.php
This changes the supporters page:
* Simplifies copy before donate form.
* Simplifies choices - leans harder into a default value (currently £10 a year). This is the only option visible unless another option is selected. 
On desktop:
On mobile, button at top are immediately visible:
Clicking the default amount gives a simplified form:
Clicking the  other gives the normal form:
> Supporters page

- www/includes/easyparliament/templates/html/mp/votes.php
Another small tidy-up fix - not relevant for current MPs, but breaking for bots that find the votes page.
> Fix error for old MPs where sig_diff_policy is null

- classes/PolicyDistributionCollection.php
Fixes an error where if the member hasn't voted, but there is a party comparison - we do not include rather
than error
(will fix typo in commit on merge)
> Do not show comparison if member hasn't voted

- tests/PartyTest.php
- www/includes/easyparliament/templates/html/mp/votes.php
We have an number of MPs where we are *only* highlighting a free vote difference. Expanding language to not imply all differences are rebellions.
> Extra MP Differs text.

- scripts/xml2db.pl
This matches the debate divisions, and will mean any non-ASCII will be HTML escaped (which is obviously stupid to do nowadays, but it at least matches).
> [PBC] Change import of names to use content rather than attribute

- classes/PolicyDistribution.php
This is handling a few new trends becoming more prominent.
- more one vote policies.
- highlighted party differences that *narrowly* cross the 60% threshold for inclusion. 
Changes made:
- Drops 'consistently' for single vote policies - can't consistently do things once. 
- Adds 'tended to vote' for votes narrowly above the threshold - there are very few of these, but important to have clear language.
- Includes alignment score for middle-ish descriptions (gives some more context on the "it's just a bit mixed").
End result looks like this:
> Adds new options to the verbose vote description

- classes/DataClass/APPGs/APPGDetails.php
- classes/DataClass/APPGs/APPGMembership.php
- classes/DataClass/APPGs/APPGMembershipAssignment.php
- classes/DataClass/APPGs/APPGMembershipList.php
- src/twfy_tools/utils/personinfo.py
- www/docs/mp/index.php
- www/includes/easyparliament/templates/html/mp/interests.php
Imports and display APPG memberships on member's interests tab.
Stores things in the personinfo table as json with name of APPG and the name of any role they might have in the APPG. Splits the display out into officer and membership sections.
Part of #1895
> load and display APPG info for MPs

- classes/DataClass/APPGs/APPGDetails.php
- classes/DataClass/APPGs/APPGMembership.php
- classes/DataClass/APPGs/APPGMembershipList.php
- classes/DataClass/BaseInterface.php
- classes/DataClass/Groups/MiniGroup.php
- classes/DataClass/Groups/MiniGroupCategoryList.php
- classes/DataClass/Groups/MiniGroupList.php
- classes/DataClass/Groups/MiniMember.php
- classes/DataClass/Groups/MiniMemberList.php
- classes/Member.php
- classes/Office.php
- locale/TheyWorkForYou.pot
- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- src/twfy_tools/utils/personinfo.py
- www/docs/mp/index.php
- www/docs/style/sass/pages/_mp.scss
- www/includes/easyparliament/templates/html/mp/_chamber_info_panel.php
- www/includes/easyparliament/templates/html/mp/_person_navigation.php
- www/includes/easyparliament/templates/html/mp/memberships.php
This builds on the new committees/appg view to bring more details into the page.
Using the new json produced by https://github.com/mysociety/parlparse/pull/233 ([can use this one](https://gist.github.com/ajparsons/8c5fbc1bdc1520ea88cf4ad33581ee9a)) - we can pull the purpose and URLs for committees into the main flow of the page.
Note: This is currently loaded as a whole json and put in memcache - good or bad approach?
Here (because are so many more), the purpose of the group is put inside a details box (which can also then include details about the source of the membership information).
I've turned back on the AI scraper results after spot checking a few (something the above makes easier). 
Bit of handholding text here and added link to form to report letters.
A few fixs to the …
> Add more details to committees/appgs

- conf/general-example
- scripts/alertmailer.php
- www/includes/easyparliament/templates/html/header.php
- www/includes/utility.php
For better tracking of "hey how many emails did we send this month/year", we want to stash the amount of emails sent in google analytics.
This uses the measurement protocol to send events - the python version of this function is here: https://github.com/mysociety/research-repository/blob/7180805ee9522c4272019357df6de4c9dc738aa7/repository/views.py#L399
In the long run, we might want to add a few more stats from the alerts (keep track of keyword/representative ones separately) - but this gets the basic approach in.
> Record emails sent in GA

- classes/User.php
- db/0029-add-user-annotation-permission.sql
- db/schema.sql
- locale/TheyWorkForYou.pot
- locale/cy_GB.UTF-8/LC_MESSAGES/TheyWorkForYou.po
- www/includes/easyparliament/templates/html/user/form.php
- www/includes/easyparliament/user.php
Adds a `can_annotate` boolean to users, plus updates the admin front end to allow editing this.
Also adds an `organisation` column to users and updates associated properties in user mode.
Fixes 1909
> add annotations permission to accounts

- classes/User.php
- tests/CommentTest.php
- tests/_fixtures/comment.xml
- www/includes/easyparliament/page.php
- www/includes/utility.php
Replaces previous custom comment parsing code with Parsedown to enable markdown formatting. Enables parsedown's safe mode to strip anything suspicious. Also does a bit of post formatting to retain nofollow links and contraction of long raw urls.
Fixes #1912
> Allow annotations to use Markdown
